### ISSUE TITLE
One error keeps repeating and preventing to do its job

### ISSUE THREAD

**Issue by MrKiller01** [ShadowJonathan/va_postal#3]
Hi again, after toying with the plugin I noticed a problem, chests with addresses do not need to stand too close to each other, and blocked chests get a sign but do not work, do not show up in the list. On top of that the route keeps telling me waypoint(0) every step I take him, even if there are 60 or so steps in the route. The mailman and his buddies are gone and on the console there are these messages:
[16:15:12 WARN]: [Postal] Plugin Postal v4.01 generated an exception while execu
ting task 322116
java.lang.NullPointerException: null
        at com.vodhanel.minecraft.va_postal.common.P_Dynmap$2.run(P_Dynmap.java:
535) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.jav
a:71) ~[spigot-1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsy
ncTask.java:52) [spigot-1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:1.8.0_144]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[16:15:18 INFO]: [ClearLag] Warning Ground items will be removed in 20 seconds!
[16:17:32 INFO]: Mr_Killer01 issued server command: /package Hightower Rec_hight
ower Mr_Killer01
[16:17:38 INFO]: Mr_Killer01 issued server command: /
[16:17:39 WARN]: [Postal] Plugin Postal v4.01 generated an exception while execu
ting task 324070
java.lang.NullPointerException: null
        at com.vodhanel.minecraft.va_postal.common.P_Dynmap$2.run(P_Dynmap.java:
535) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.jav
a:71) ~[spigot-1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsy
ncTask.java:52) [spigot-1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:1.8.0_144]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[16:18:28 INFO]: Mr_Killer01 issued server command: /package Hightower Rec_hight
ower Mr_Killer01
[16:18:31 INFO]: Mr_Killer01 issued server command: /
[16:20:06 WARN]: [Postal] Plugin Postal v4.01 generated an exception while execu
ting task 326254
java.lang.NullPointerException: null
        at com.vodhanel.minecraft.va_postal.common.P_Dynmap$2.run(P_Dynmap.java:
535) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.jav
a:71) ~[spigot-1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsy
ncTask.java:52) [spigot-1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:1.8.0_144]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
		
		[16:00:28 WARN]: [Postal] Plugin Postal v4.01 generated an exception while execu
ting task 310099
java.lang.NullPointerException: null
        at com.vodhanel.minecraft.va_postal.common.P_Dynmap$2.run(P_Dynmap.java:
535) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.jav
a:71) ~[spigot-1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsy
ncTask.java:52) [spigot-1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:1.8.0_144]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[16:02:56 WARN]: [Postal] Plugin Postal v4.01 generated an exception while execu
ting task 312117
java.lang.NullPointerException: null
        at com.vodhanel.minecraft.va_postal.common.P_Dynmap$2.run(P_Dynmap.java:
535) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.jav
a:71) ~[spigot-1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsy
ncTask.java:52) [spigot-1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:1.8.0_144]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[16:05:23 WARN]: [Postal] Plugin Postal v4.01 generated an exception while execu
ting task 314071
java.lang.NullPointerException: null
        at com.vodhanel.minecraft.va_postal.common.P_Dynmap$2.run(P_Dynmap.java:
535) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.jav
a:71) ~[spigot-1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsy
ncTask.java:52) [spigot-1.12.2.jar:git-Spigot-d21162c-82f3b02]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:1.8.0_144]

**Comment by ShadowJonathan** [comment]
I see, the waypoint messages are some leftover debug messages, the chest problem was something I noticed while checking the code, so that'll be buggy for a while (could you give me more screenshots of where chests do weird things? maybe in a different issue?)

the error right there looks like somethings wrong with dynmap, I'll look at it, but do you have it installed by any chance?

**Comment by MrKiller01** [comment]
Again, sorry for late response, I have since the end of February two servers to host, and converted it to bungeecord, so, i've been busy...
I do have dynmap installed on both servers, the one i had the error with, is going to be updated left and right some plugins, but as the other issue I posted, I will go test postal again, from fresh point....

**Comment by MrKiller01** [comment]
As the former reaction of me told you, i've found with this version no problems anymore. So, i'm closing this one, leaving the other one open for answering...
Thanks for your input and time....
