### ISSUE TITLE
Possible Citizens generating error when delivering mail

### ISSUE THREAD

**Issue by GuiltyWatts** [ShadowJonathan/va_postal#5]
With the update, we can now address mail and set ownership of mailboxes. However, when we send mail, it goes from the central post office to the local post office, but when the post man goes out, he gets to the mailbox and freezes. Nothing happens. In the console, I see this error:

02.12 18:21:24 [Server] INFO [Citizens] Exception while updating 108: 15.
02.12 18:21:24 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 15
02.12 18:21:24 [Server] WARN at com.vodhanel.minecraft.va_postal.mail.Book.extractEmbeddedReceipient(Book.java:247)
02.12 18:21:24 [Server] WARN at com.vodhanel.minecraft.va_postal.mail.ID_Mail.stamp_deliver(ID_Mail.java:742)
02.12 18:21:24 [Server] WARN at com.vodhanel.minecraft.va_postal.mail.ID_Mail.npc_deliver_mail(ID_Mail.java:701)
02.12 18:21:24 [Server] WARN at com.vodhanel.minecraft.va_postal.navigation.ID_WTR.arrived_at_address(ID_WTR.java:120)
02.12 18:21:24 [Server] WARN at com.vodhanel.minecraft.va_postal.navigation.ID_WTR.increment_to_next_waypoint(ID_WTR.java:676)
02.12 18:21:24 [Server] WARN at com.vodhanel.minecraft.va_postal.navigation.ID_WTR.invoke_next_waypoint(ID_WTR.java:369)
02.12 18:21:24 [Server] WARN at com.vodhanel.minecraft.va_postal.navigation.Goal_WTR.run(Goal_WTR.java:111)
02.12 18:21:24 [Server] WARN at net.citizensnpcs.api.ai.SimpleGoalController.run(SimpleGoalController.java:185)
02.12 18:21:24 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:433)
02.12 18:21:24 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:268)
02.12 18:21:24 [Server] WARN at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:158)
02.12 18:21:24 [Server] WARN at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1633)
02.12 18:21:24 [Server] WARN at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1025)
02.12 18:21:24 [Server] WARN at net.citizensnpcs.util.NMS.tick(NMS.java:294)
02.12 18:21:24 [Server] WARN at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36)
02.12 18:21:24 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
02.12 18:21:24 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
02.12 18:21:24 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
02.12 18:21:24 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
02.12 18:21:24 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
02.12 18:21:24 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
02.12 18:21:24 [Server] WARN at java.lang.Thread.run(Thread.java:748)

i cant really tell if Citizens is at fault or Postal.

**Comment by Serpano** [comment]
i have the same error please fix it!!!
