### ISSUE TITLE
Error when creating local post office.

### ISSUE THREAD

**Issue by ClockLoop** [ShadowJonathan/va_postal#6]
1:10:27 AM [INFO]
![new bitmap image](https://user-images.githubusercontent.com/13613660/40643852-92e2acee-62de-11e8-8b24-68cddfc86e71.jpg)

User issued server command: /

1:10:27 AM [ERROR] null

1:10:27 AM org.bukkit.command.CommandException: Unhandled exception executing command 'setlocal' in plugin Postal v4.01

1:10:27 AM at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-
1.12.2.jar:git-Spigot-2086bb0-d0a3620]

1:10:27 AM at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]

1:10:27 AM at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]

1:10:27 AM at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]

1:10:27 AM at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]

1:10:27 AM at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]

1:10:27 AM at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]

1:10:27 AM at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]

1:10:27 AM at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]

1:10:27 AM at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]

1:10:27 AM at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]

1:10:27 AM at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]

1:10:27 AM at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]

1:10:27 AM at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]

1:10:27 AM at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]

1:10:27 AM at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

1:10:27 AM Caused by: java.lang.ClassCastException: com.palmergames.bukkit.towny.object.Resident cannot be cast to org.bukkit.entity.Player

1:10:27 AM at com.vodhanel.minecraft.va_postal.common.P_Towny.towny_mayor_by_loc(P_Towny.java:699) ~[?:?]

1:10:27 AM at com.vodhanel.minecraft.va_postal.commands.Cmdexecutor.setlocal(Cmdexecutor.java:1046) ~[?:?]

1:10:27 AM at com.vodhanel.minecraft.va_postal.commands.Cmdexecutor.onCommand(Cmdexecutor.java:2737) ~[?:?]

1:10:27 AM at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]

1:10:27 AM ... 15 more

**Comment by mginn** [comment]
Was doing my own independent analysis. Looks like the program is breaking in more recent versions of minecraft. Books in minecraft now can at most be 14 lines. The plugin tries to write 15 which breaks lots of things and throws lots of errors. I am making my own edits to fix this since I too really like this plugin.
